### ISSUE TITLE
[BUG] - Don't allow listing upgrades without providing cluster UUID

### ISSUE THREAD

**Issue by optik-aper** [vultr/vultr-cli#497]
**Describe the bug**
When running `kubernetes upgrade list` and not including a UUID
```
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/vultr/vultr-cli/v3/cmd/kubernetes.(*options).upgrades(0x0?)
        /home/michael/repos/vultr-cli/cmd/kubernetes/kubernetes.go:1215 +0x59
github.com/vultr/vultr-cli/v3/cmd/kubernetes.NewCmdKubernetes.func14(0xc000235700?, {0xe4fa80?, 0x4?, 0x9e51f1?})
        /home/michael/repos/vultr-cli/cmd/kubernetes/kubernetes.go:605 +0x25
github.com/spf13/cobra.(*Command).execute(0xc0001e9508, {0xe4fa80, 0x0, 0x0})
        /home/michael/repos/vultr-cli/vendor/github.com/spf13/cobra/command.go:985 +0xaaa
github.com/spf13/cobra.(*Command).ExecuteC(0xe287a0)
        /home/michael/repos/vultr-cli/vendor/github.com/spf13/cobra/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        /home/michael/repos/vultr-cli/vendor/github.com/spf13/cobra/command.go:1041
github.com/vultr/vultr-cli/v3/cmd.Execute()
        /home/michael/repos/vultr-cli/cmd/root.go:64 +0x1a
main.main()
        /home/michael/repos/vultr-cli/main.go:7 +0xf
exit status 2
```

**Expected behavior**
Make the UUID required

**Comment by kanha-gupta** [comment]
Please assign this to me
