### ISSUE TITLE
[BUG] - Don't allow "container-registry credentials docker" without providing registry UUID

### ISSUE THREAD

**Issue by benok** [vultr/vultr-cli#498]
Hi, I found another one like #497.

**Describe the bug**
When running `container-registry credentials docker` and not including a UUID

```log
$ vultr-cli container-registry credentials docker
panic: runtime error: index out of range [0] with length 0

goroutine 1 [running]:
github.com/vultr/vultr-cli/v3/cmd/containerregistry.(*options).credentialsDocker(0xc00011a200?)
        github.com/vultr/vultr-cli/v3/cmd/containerregistry/containerregistry.go:713 +0x65
github.com/vultr/vultr-cli/v3/cmd/containerregistry.NewCmdContainerRegistry.func20(0xc000117808, {0xdf9840?, 0x4?, 0x98edea?})
        github.com/vultr/vultr-cli/v3/cmd/containerregistry/containerregistry.go:597 +0x1bc
github.com/spf13/cobra.(*Command).execute(0xc000117808, {0xdf9840, 0x0, 0x0})
        github.com/spf13/cobra@v1.8.1/command.go:985 +0xaca
github.com/spf13/cobra.(*Command).ExecuteC(0xd92f80)
        github.com/spf13/cobra@v1.8.1/command.go:1117 +0x3ff
github.com/spf13/cobra.(*Command).Execute(...)
        github.com/spf13/cobra@v1.8.1/command.go:1041
github.com/vultr/vultr-cli/v3/cmd.Execute()
        github.com/vultr/vultr-cli/v3/cmd/root.go:64 +0x1a
main.main()
        github.com/vultr/vultr-cli/v3/main.go:7 +0xf
```

**Expected behavior**
Make the UUID required

**Comment by kanha-gupta** [comment]
I am raising a PR for this
